services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/home/vscode/app:cached
      - venv:/home/vscode/app/.venv
    tty: true
    stdin_open: true
    environment:
      ATMOS_API_URL: https://atmos-staging.qleap.jp

volumes:
  venv:
    driver: local
